include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - ".dart_tool/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "android/**"
    - "ios/**"
    - "linux/**"
    - "macos/**"
    - "web/**"
    - "windows/**"
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: warning
